// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-JAVRJgnOd-wU0hle54MVIOUmjTZxt4A',
    appId: '1:422436439009:web:594b5e2a5608b4f33908a0',
    messagingSenderId: '422436439009',
    projectId: 'nutsnbolts-1',
    authDomain: 'nutsnbolts-1.firebaseapp.com',
    storageBucket: 'nutsnbolts-1.appspot.com',
    measurementId: 'G-WM4QGE43J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp3JhOUcp9myGc1tvc9_4KOGkZ4VSxbE4',
    appId: '1:422436439009:android:cb46fbb11d18f4443908a0',
    messagingSenderId: '422436439009',
    projectId: 'nutsnbolts-1',
    storageBucket: 'nutsnbolts-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTNBYciPBxE5aC3lfD3Z8LkUAiHCFLTK8',
    appId: '1:422436439009:ios:58ad5b62b579317b3908a0',
    messagingSenderId: '422436439009',
    projectId: 'nutsnbolts-1',
    storageBucket: 'nutsnbolts-1.appspot.com',
    iosClientId: '422436439009-bacvmlettl1l9meo542p289t9k0htnpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutsnbolts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTNBYciPBxE5aC3lfD3Z8LkUAiHCFLTK8',
    appId: '1:422436439009:ios:58ad5b62b579317b3908a0',
    messagingSenderId: '422436439009',
    projectId: 'nutsnbolts-1',
    storageBucket: 'nutsnbolts-1.appspot.com',
    iosClientId: '422436439009-bacvmlettl1l9meo542p289t9k0htnpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutsnbolts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-JAVRJgnOd-wU0hle54MVIOUmjTZxt4A',
    appId: '1:422436439009:web:646c0c7c79e2a35e3908a0',
    messagingSenderId: '422436439009',
    projectId: 'nutsnbolts-1',
    authDomain: 'nutsnbolts-1.firebaseapp.com',
    storageBucket: 'nutsnbolts-1.appspot.com',
    measurementId: 'G-RJ4CW5067D',
  );
}
